import { EstoqueItem } from "./types";

// Gerado a partir de 'ESTOQUE - LA NA CABANINHA.xlsx' (dados reais da cliente)
export const estoqueInicial: EstoqueItem[] = [
  { id: "est-cabanas-amarela", categoria: "Cabanas", nome: "Amarela", quantidade: 3 },
  { id: "est-cabanas-azul-claro", categoria: "Cabanas", nome: "Azul Claro", quantidade: 9 },
  { id: "est-cabanas-azul-marinho", categoria: "Cabanas", nome: "Azul Marinho", quantidade: 1 },
  { id: "est-cabanas-azul-tiffany-poa", categoria: "Cabanas", nome: "Azul Tiffany Poá", quantidade: 4 },
  { id: "est-cabanas-bege-com-verde-musgo-e-animais", categoria: "Cabanas", nome: "Bege Com Verde Musgo E Animais", quantidade: 1 },
  { id: "est-cabanas-bege-tecido", categoria: "Cabanas", nome: "Bege Tecido", quantidade: 18 },
  { id: "est-cabanas-branca-cetim-floral", categoria: "Cabanas", nome: "Branca Cetim Floral", quantidade: 3 },
  { id: "est-cabanas-branca-lisa", categoria: "Cabanas", nome: "Branca Lisa", quantidade: 2 },
  { id: "est-cabanas-branca-poa", categoria: "Cabanas", nome: "Branca Poá", quantidade: 4 },
  { id: "est-cabanas-camuflada-tactel", categoria: "Cabanas", nome: "Camuflada Tactel", quantidade: 8 },
  { id: "est-cabanas-camuflada-tecido", categoria: "Cabanas", nome: "Camuflada Tecido", quantidade: 6 },
  { id: "est-cabanas-chevron-azul-marinho-branco", categoria: "Cabanas", nome: "Chevron Azul Marinho/Branco", quantidade: 2 },
  { id: "est-cabanas-chevron-azul-azul-bebe", categoria: "Cabanas", nome: "Chevron Azul/Azul Bebê", quantidade: 1 },
  { id: "est-cabanas-chevron-branca-rose", categoria: "Cabanas", nome: "Chevron Branca/Rosê", quantidade: 1 },
  { id: "est-cabanas-chevron-branca-verde", categoria: "Cabanas", nome: "Chevron Branca/Verde", quantidade: 1 },
  { id: "est-cabanas-chevron-c-poa-azul-bebe", categoria: "Cabanas", nome: "Chevron C/ Poá Azul Bebê", quantidade: 1 },
  { id: "est-cabanas-chevron-laranja-cinza-verde-branca", categoria: "Cabanas", nome: "Chevron Laranja/Cinza/Verde/Branca", quantidade: 1 },
  { id: "est-cabanas-cinza-poa", categoria: "Cabanas", nome: "Cinza Poá", quantidade: 3 },
  { id: "est-cabanas-floral-azul-rosa", categoria: "Cabanas", nome: "Floral Azul/Rosa", quantidade: 2 },
  { id: "est-cabanas-jeans", categoria: "Cabanas", nome: "Jeans", quantidade: 8 },
  { id: "est-cabanas-laranja-neon", categoria: "Cabanas", nome: "Laranja Neon", quantidade: 2 },
  { id: "est-cabanas-lilas-clara", categoria: "Cabanas", nome: "Lilás Clara", quantidade: 4 },
  { id: "est-cabanas-lilas-escura", categoria: "Cabanas", nome: "Lilás Escura", quantidade: 3 },
  { id: "est-cabanas-lilas-media", categoria: "Cabanas", nome: "Lilás Média", quantidade: 2 },
  { id: "est-cabanas-lilas-poa", categoria: "Cabanas", nome: "Lilás Poá", quantidade: 2 },
  { id: "est-cabanas-poa-vermelho", categoria: "Cabanas", nome: "Poá Vermelho", quantidade: 1 },
  { id: "est-cabanas-preta", categoria: "Cabanas", nome: "Preta", quantidade: 4 },
  { id: "est-cabanas-renda-bege", categoria: "Cabanas", nome: "Renda Bege", quantidade: 1 },
  { id: "est-cabanas-rosa-claro", categoria: "Cabanas", nome: "Rosa Claro", quantidade: 9 },
  { id: "est-cabanas-rosa-claro-chevron-com-poa", categoria: "Cabanas", nome: "Rosa Claro Chevron Com Poá", quantidade: 6 },
  { id: "est-cabanas-rosa-claro-com-nuvens-brancas", categoria: "Cabanas", nome: "Rosa Claro Com Nuvens Brancas", quantidade: 3 },
  { id: "est-cabanas-rosa-escuro-pink", categoria: "Cabanas", nome: "Rosa Escuro (Pink)", quantidade: 4 },
  { id: "est-cabanas-rosa-escuro-com-nuvens-brancas", categoria: "Cabanas", nome: "Rosa Escuro Com Nuvens Brancas", quantidade: 2 },
  { id: "est-cabanas-rosa-neon", categoria: "Cabanas", nome: "Rosa Neon", quantidade: 3 },
  { id: "est-cabanas-rose-cetim-floral", categoria: "Cabanas", nome: "Rosê Cetim Floral", quantidade: 2 },
  { id: "est-cabanas-roxa", categoria: "Cabanas", nome: "Roxa", quantidade: 3 },
  { id: "est-cabanas-roxa-poa", categoria: "Cabanas", nome: "Roxa Poá", quantidade: 2 },
  { id: "est-cabanas-salmao-com-nuvens-brancas", categoria: "Cabanas", nome: "Salmão Com Nuvens Brancas", quantidade: 2 },
  { id: "est-cabanas-snoopy", categoria: "Cabanas", nome: "Snoopy", quantidade: 2 },
  { id: "est-cabanas-triangulos-cinza-rosa-branco", categoria: "Cabanas", nome: "Triangulos Cinza/Rosa/Branco", quantidade: 2 },
  { id: "est-cabanas-verde", categoria: "Cabanas", nome: "Verde", quantidade: 1 },
  { id: "est-cabanas-verde-agua", categoria: "Cabanas", nome: "Verde Agua", quantidade: 6 },
  { id: "est-cabanas-verde-musgo-camuflata-tecido", categoria: "Cabanas", nome: "Verde Musgo/Camuflata Tecido", quantidade: 3 },
  { id: "est-cabanas-verde-neon", categoria: "Cabanas", nome: "Verde Neon", quantidade: 3 },
  { id: "est-cabanas-vermelha", categoria: "Cabanas", nome: "Vermelha", quantidade: 4 },
  { id: "est-tendas-armacao-armacao-tenda-grde", categoria: "Tendas — Armação", nome: "Armação Tenda Grde", quantidade: 2 },
  { id: "est-tendas-armacao-armacao-tenda-pq", categoria: "Tendas — Armação", nome: "Armação Tenda Pq", quantidade: 1 },
  { id: "est-tendas-armacao-pecas-tenda-gde", categoria: "Tendas — Armação", nome: "Peças Tenda Gde", quantidade: 2, nota: "2 KIT OK" },
  { id: "est-tendas-armacao-canos-com-areia-pro-tecido", categoria: "Tendas — Armação", nome: "Canos Com Areia Pro Tecido", quantidade: 2 },
  { id: "est-tendas-tecidos-branco-de-amarrar", categoria: "Tendas — Tecidos", nome: "Branco De Amarrar", quantidade: 1 },
  { id: "est-tendas-tecidos-roxo-de-elanca", categoria: "Tendas — Tecidos", nome: "Roxo De Elanca", quantidade: 1 },
  { id: "est-tendas-tecidos-azul-de-elanca", categoria: "Tendas — Tecidos", nome: "Azul De Elanca", quantidade: 1 },
  { id: "est-tendas-tecidos-branco-de-veu", categoria: "Tendas — Tecidos", nome: "Branco De Véu", quantidade: 1 },
  { id: "est-tendas-tecidos-roxo-de-veu", categoria: "Tendas — Tecidos", nome: "Roxo De Véu", quantidade: 1 },
  { id: "est-tendas-tecidos-rosa-de-veu", categoria: "Tendas — Tecidos", nome: "Rosa De Véu", quantidade: 1 },
  { id: "est-travesseiros-travesseiros-unidades", categoria: "Travesseiros", nome: "Travesseiros (Unidades)", quantidade: 87 },
  { id: "est-fronhas-cetim-rose", categoria: "Fronhas", nome: "Cetim Rosê", quantidade: 14 },
  { id: "est-fronhas-olhinho", categoria: "Fronhas", nome: "Olhinho", quantidade: 22 },
  { id: "est-fronhas-cetim-pink", categoria: "Fronhas", nome: "Cetim Pink", quantidade: 5 },
  { id: "est-fronhas-verde-agua", categoria: "Fronhas", nome: "Verde Agua", quantidade: 16 },
  { id: "est-fronhas-verde-abacate", categoria: "Fronhas", nome: "Verde Abacate", quantidade: 4 },
  { id: "est-fronhas-verde-musgo", categoria: "Fronhas", nome: "Verde Musgo", quantidade: 4 },
  { id: "est-fronhas-verde-claro", categoria: "Fronhas", nome: "Verde Claro", quantidade: 14 },
  { id: "est-fronhas-azul-marinho", categoria: "Fronhas", nome: "Azul Marinho", quantidade: 2 },
  { id: "est-fronhas-azul-petroleo", categoria: "Fronhas", nome: "Azul Petróleo", quantidade: 8 },
  { id: "est-fronhas-azul-bebe", categoria: "Fronhas", nome: "Azul Bebê", quantidade: 13 },
  { id: "est-fronhas-azul-cetim", categoria: "Fronhas", nome: "Azul Cetim", quantidade: 10 },
  { id: "est-fronhas-vermelho", categoria: "Fronhas", nome: "Vermelho", quantidade: 12 },
  { id: "est-fronhas-lilas-escuro", categoria: "Fronhas", nome: "Lilás Escuro", quantidade: 17 },
  { id: "est-fronhas-lilas-claro", categoria: "Fronhas", nome: "Lilás Claro", quantidade: 8 },
  { id: "est-fronhas-lilas-cetim", categoria: "Fronhas", nome: "Lilás Cetim", quantidade: 10 },
  { id: "est-fronhas-rosa-claro", categoria: "Fronhas", nome: "Rosa Claro", quantidade: 12 },
  { id: "est-fronhas-pink", categoria: "Fronhas", nome: "Pink", quantidade: 28 },
  { id: "est-fronhas-rosa-chiclete", categoria: "Fronhas", nome: "Rosa Chiclete", quantidade: 12 },
  { id: "est-fronhas-rosa-poa", categoria: "Fronhas", nome: "Rosa Poá", quantidade: 10 },
  { id: "est-fronhas-preto", categoria: "Fronhas", nome: "Preto", quantidade: 14 },
  { id: "est-fronhas-amarelo", categoria: "Fronhas", nome: "Amarelo", quantidade: 8 },
  { id: "est-fronhas-branco", categoria: "Fronhas", nome: "Branco", quantidade: 32 },
  { id: "est-fronhas-laranja", categoria: "Fronhas", nome: "Laranja", quantidade: 1 },
  { id: "est-fronhas-estampado", categoria: "Fronhas", nome: "Estampado", quantidade: 1 },
  { id: "est-cobertores-casal-off-white", categoria: "Cobertores Casal", nome: "Off White", quantidade: 19 },
  { id: "est-cobertores-solteiro-bege", categoria: "Cobertores Solteiro", nome: "Bege", quantidade: 7 },
  { id: "est-cobertores-casal-marrom", categoria: "Cobertores Casal", nome: "Marrom", quantidade: 15 },
  { id: "est-cobertores-solteiro-preto", categoria: "Cobertores Solteiro", nome: "Preto", quantidade: 3 },
  { id: "est-cobertores-casal-branco", categoria: "Cobertores Casal", nome: "Branco", quantidade: 1 },
  { id: "est-cobertores-solteiro-vermelho", categoria: "Cobertores Solteiro", nome: "Vermelho", quantidade: 14 },
  { id: "est-cobertores-casal-cinza", categoria: "Cobertores Casal", nome: "Cinza", quantidade: 2 },
  { id: "est-cobertores-solteiro-verde-abacate", categoria: "Cobertores Solteiro", nome: "Verde Abacate", quantidade: 10 },
  { id: "est-cobertores-casal-rosa-que-brlha", categoria: "Cobertores Casal", nome: "Rosa Que Brlha", quantidade: 2 },
  { id: "est-cobertores-solteiro-amarelo", categoria: "Cobertores Solteiro", nome: "Amarelo", quantidade: 10 },
  { id: "est-cobertores-casal-preto", categoria: "Cobertores Casal", nome: "Preto", quantidade: 6 },
  { id: "est-cobertores-solteiro-azul-royal", categoria: "Cobertores Solteiro", nome: "Azul Royal", quantidade: 7 },
  { id: "est-cobertores-casal-vermelho", categoria: "Cobertores Casal", nome: "Vermelho", quantidade: 3 },
  { id: "est-cobertores-solteiro-azul-marinho", categoria: "Cobertores Solteiro", nome: "Azul Marinho", quantidade: 7 },
  { id: "est-cobertores-casal-verde-agua-novo", categoria: "Cobertores Casal", nome: "Verde Agua Novo", quantidade: 2 },
  { id: "est-cobertores-solteiro-azul-bebe", categoria: "Cobertores Solteiro", nome: "Azul Bebe", quantidade: 4 },
  { id: "est-cobertores-casal-verde-agua", categoria: "Cobertores Casal", nome: "Verde Agua", quantidade: 9 },
  { id: "est-cobertores-solteiro-roxo-mini", categoria: "Cobertores Solteiro", nome: "Roxo Mini", quantidade: 6 },
  { id: "est-cobertores-casal-azul-tiffany", categoria: "Cobertores Casal", nome: "Azul Tiffany", quantidade: 9 },
  { id: "est-cobertores-solteiro-borboleta-mini", categoria: "Cobertores Solteiro", nome: "Borboleta Mini", quantidade: 3 },
  { id: "est-cobertores-casal-azul-claro", categoria: "Cobertores Casal", nome: "Azul Claro", quantidade: 2 },
  { id: "est-cobertores-solteiro-rosa-bebe", categoria: "Cobertores Solteiro", nome: "Rosa Bebe", quantidade: 12 },
  { id: "est-cobertores-casal-rosa-lilas", categoria: "Cobertores Casal", nome: "Rosa / Lilás", quantidade: 8 },
  { id: "est-cobertores-solteiro-pink", categoria: "Cobertores Solteiro", nome: "Pink", quantidade: 13 },
  { id: "est-cobertores-casal-lilas-claro", categoria: "Cobertores Casal", nome: "Lilás Claro", quantidade: 4 },
  { id: "est-cobertores-casal-roxo-azulado", categoria: "Cobertores Casal", nome: "Roxo Azulado", quantidade: 2 },
  { id: "est-cobertores-casal-lilas-com-pompom", categoria: "Cobertores Casal", nome: "Lilás Com Pompom", quantidade: 1 },
  { id: "est-cobertores-casal-rose", categoria: "Cobertores Casal", nome: "Rosê", quantidade: 5 },
  { id: "est-cobertores-casal-pink", categoria: "Cobertores Casal", nome: "Pink", quantidade: 18 },
  { id: "est-cobertores-casal-vinho", categoria: "Cobertores Casal", nome: "Vinho", quantidade: 6 },
  { id: "est-cobertores-casal-roxo-liso", categoria: "Cobertores Casal", nome: "Roxo Liso", quantidade: 3 },
  { id: "est-cobertores-casal-roxo-felpudo", categoria: "Cobertores Casal", nome: "Roxo Felpudo", quantidade: 4 },
  { id: "est-cobertores-casal-roxo-vinho", categoria: "Cobertores Casal", nome: "Roxo / Vinho", quantidade: 5 },
  { id: "est-almofadas-stitch-quadrada", categoria: "Almofadas", nome: "Stitch Quadrada", quantidade: 13 },
  { id: "est-almofadas-stitch-formato-gde", categoria: "Almofadas", nome: "Stitch Formato Gde", quantidade: 3 },
  { id: "est-almofadas-stitch-formato-pq", categoria: "Almofadas", nome: "Stitch Formato Pq", quantidade: 8 },
  { id: "est-almofadas-rosa", categoria: "Almofadas", nome: "Rosa", quantidade: 7 },
  { id: "est-almofadas-rosa-pelucia", categoria: "Almofadas", nome: "Rosa Pelúcia", quantidade: 1 },
  { id: "est-almofadas-rosa-cetim", categoria: "Almofadas", nome: "Rosa Cetim", quantidade: 4 },
  { id: "est-almofadas-amarelo-neon", categoria: "Almofadas", nome: "Amarelo Neon", quantidade: 2 },
  { id: "est-almofadas-laranja-neon", categoria: "Almofadas", nome: "Laranja Neon", quantidade: 4 },
  { id: "est-almofadas-rosa-neon", categoria: "Almofadas", nome: "Rosa Neon", quantidade: 7 },
  { id: "est-almofadas-vermelha", categoria: "Almofadas", nome: "Vermelha", quantidade: 3 },
  { id: "est-almofadas-azul-royal", categoria: "Almofadas", nome: "Azul Royal", quantidade: 3 },
  { id: "est-almofadas-verde", categoria: "Almofadas", nome: "Verde", quantidade: 3 },
  { id: "est-almofadas-roxa", categoria: "Almofadas", nome: "Roxa", quantidade: 2 },
  { id: "est-almofadas-bege-de-pelo", categoria: "Almofadas", nome: "Bege De Pelo", quantidade: 4 },
  { id: "est-almofadas-verde-rosa-lantejoula", categoria: "Almofadas", nome: "Verde/Rosa Lantejoula", quantidade: 5 },
  { id: "est-almofadas-azul-marinho", categoria: "Almofadas", nome: "Azul Marinho", quantidade: 4 },
  { id: "est-almofadas-verde-agua", categoria: "Almofadas", nome: "Verde Agua", quantidade: 2 },
  { id: "est-almofadas-lilas", categoria: "Almofadas", nome: "Lilás", quantidade: 1 },
  { id: "est-almofadas-camuflada", categoria: "Almofadas", nome: "Camuflada", quantidade: 14 },
  { id: "est-almofadas-jeans", categoria: "Almofadas", nome: "Jeans", quantidade: 14 },
  { id: "est-almofadas-planetas-fundo-preto", categoria: "Almofadas", nome: "Planetas Fundo Preto", quantidade: 5 },
  { id: "est-almofadas-minions-amarela", categoria: "Almofadas", nome: "Minions Amarela", quantidade: 2 },
  { id: "est-almofadas-no-rose", categoria: "Almofadas", nome: "Nó Rosê", quantidade: 3 },
  { id: "est-almofadas-palmeiras", categoria: "Almofadas", nome: "Palmeiras", quantidade: 1 },
  { id: "est-almofadas-mini-colchonetes", categoria: "Almofadas", nome: "Mini Colchonetes", quantidade: 17 },
  { id: "est-almofadas-rose-pelinhos", categoria: "Almofadas", nome: "Rosê Pelinhos", quantidade: 1 },
  { id: "est-almofadas-lua-estrela-nuvem-branca-pelucia", categoria: "Almofadas", nome: "Lua / Estrela /  Nuvem Branca Pelúcia", quantidade: 3 },
  { id: "est-almofadas-harry-potter-mini-amarela-marrom-vermelha-azul", categoria: "Almofadas", nome: "Harry Potter Mini Amarela / Marrom / Vermelha / Azul", quantidade: 4 },
  { id: "est-almofadas-coruja-mini", categoria: "Almofadas", nome: "Coruja Mini", quantidade: 4 },
  { id: "est-almofadas-panda-mini", categoria: "Almofadas", nome: "Panda Mini", quantidade: 4 },
  { id: "est-almofadas-divertidamente-mini", categoria: "Almofadas", nome: "Divertidamente Mini", quantidade: 2 },
  { id: "est-almofadas-pascoa-mini", categoria: "Almofadas", nome: "Páscoa Mini", quantidade: 2 },
  { id: "est-almofadas-formato-de-unicornio", categoria: "Almofadas", nome: "Formato De Unicórnio", quantidade: 4 },
  { id: "est-almofadas-formato-de-coruja", categoria: "Almofadas", nome: "Formato De Coruja", quantidade: 1 },
  { id: "est-almofadas-formato-de-coracao-verde", categoria: "Almofadas", nome: "Formato De Coração Verde", quantidade: 5 },
  { id: "est-almofadas-formato-de-coracao-azul", categoria: "Almofadas", nome: "Formato De Coração Azul", quantidade: 3 },
  { id: "est-almofadas-formato-de-coracao-lilas", categoria: "Almofadas", nome: "Formato De Coração Lilás", quantidade: 8 },
  { id: "est-almofadas-formato-de-coracao-amarelo", categoria: "Almofadas", nome: "Formato De Coração Amarelo", quantidade: 2 },
  { id: "est-almofadas-formato-de-coracao-pink", categoria: "Almofadas", nome: "Formato De Coração Pink", quantidade: 3 },
  { id: "est-almofadas-formato-de-coracao-rosa-bebe", categoria: "Almofadas", nome: "Formato De Coração Rosa Bebê", quantidade: 3 },
  { id: "est-almofadas-formato-de-coracao-rosa-escuro", categoria: "Almofadas", nome: "Formato De Coração Rosa Escuro", quantidade: 5 },
  { id: "est-lencois-branco-elastico", categoria: "Lençóis", nome: "Branco Elástico", quantidade: 54 },
  { id: "est-lencois-branco", categoria: "Lençóis", nome: "Branco", quantidade: 44 },
  { id: "est-lencois-rosa-claro", categoria: "Lençóis", nome: "Rosa Claro", quantidade: 8 },
  { id: "est-lencois-jeans", categoria: "Lençóis", nome: "Jeans", quantidade: 7 },
  { id: "est-lencois-pink", categoria: "Lençóis", nome: "Pink", quantidade: 3 },
  { id: "est-lencois-roxo", categoria: "Lençóis", nome: "Roxo", quantidade: 3 },
  { id: "est-lencois-lilas", categoria: "Lençóis", nome: "Lilás", quantidade: 3 },
  { id: "est-iluminacao-flor-branca", categoria: "Iluminação", nome: "Flor Branca", quantidade: 10 },
  { id: "est-iluminacao-flor-branca-e-rosa", categoria: "Iluminação", nome: "Flor Branca E Rosa", quantidade: 6 },
  { id: "est-iluminacao-bola-grande-colorida", categoria: "Iluminação", nome: "Bola Grande Colorida", quantidade: 11 },
  { id: "est-iluminacao-bola-grande-amarela-de-pilha", categoria: "Iluminação", nome: "Bola Grande Amarela De Pilha", quantidade: 12 },
  { id: "est-iluminacao-bola-grande-amarela-de-tomada", categoria: "Iluminação", nome: "Bola Grande Amarela De Tomada", quantidade: 4 },
  { id: "est-iluminacao-bolinha-pq-branca", categoria: "Iluminação", nome: "Bolinha Pq Branca", quantidade: 13 },
  { id: "est-iluminacao-bolinha-pq-transparente", categoria: "Iluminação", nome: "Bolinha Pq Transparente", quantidade: 5 },
  { id: "est-iluminacao-pregador", categoria: "Iluminação", nome: "Pregador", quantidade: 4 },
  { id: "est-iluminacao-estrela", categoria: "Iluminação", nome: "Estrela", quantidade: 4 },
  { id: "est-iluminacao-lampada-pontuda-branca-c-fio-preto-colorida", categoria: "Iluminação", nome: "Lampada Pontuda Branca C/ Fio Preto Colorida", quantidade: 2 },
  { id: "est-iluminacao-bola-linha-azul", categoria: "Iluminação", nome: "Bola Linha Azul", quantidade: 8 },
  { id: "est-iluminacao-bola-linha-branca-e-rosa", categoria: "Iluminação", nome: "Bola Linha Branca E Rosa", quantidade: 2 },
  { id: "est-iluminacao-rola-linha-rosa", categoria: "Iluminação", nome: "Rola Linha Rosa", quantidade: 1 },
  { id: "est-iluminacao-bola-linha-branca", categoria: "Iluminação", nome: "Bola Linha Branca", quantidade: 1 },
  { id: "est-iluminacao-bola-pq-colorida", categoria: "Iluminação", nome: "Bola Pq Colorida", quantidade: 1 },
  { id: "est-iluminacao-bola-pq-preta", categoria: "Iluminação", nome: "Bola Pq Preta", quantidade: 3 },
  { id: "est-iluminacao-coracoes-rosa-branco-pilha", categoria: "Iluminação", nome: "Corações Rosa/Branco Pilha", quantidade: 2 },
  { id: "est-iluminacao-coracoes-vermelho-tomada", categoria: "Iluminação", nome: "Corações Vermelho Tomada", quantidade: 1 },
  { id: "est-iluminacao-lanterna-japonesa-verde", categoria: "Iluminação", nome: "Lanterna Japonesa Verde", quantidade: 1 },
  { id: "est-iluminacao-lanterna-japonesa-branca", categoria: "Iluminação", nome: "Lanterna Japonesa Branca", quantidade: 2 },
  { id: "est-iluminacao-lanterna-japonesa-rosa", categoria: "Iluminação", nome: "Lanterna Japonesa Rosa", quantidade: 1 },
  { id: "est-iluminacao-cup-cake", categoria: "Iluminação", nome: "Cup Cake", quantidade: 2 },
  { id: "est-iluminacao-flamingo", categoria: "Iluminação", nome: "Flamingo", quantidade: 3 },
  { id: "est-iluminacao-panda", categoria: "Iluminação", nome: "Panda", quantidade: 1 },
  { id: "est-iluminacao-flores", categoria: "Iluminação", nome: "Flores", quantidade: 1 },
  { id: "est-iluminacao-letras", categoria: "Iluminação", nome: "Letras", quantidade: 1 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-rosa", categoria: "Iluminação", nome: "Fio De Luz De Tomada Rosa", quantidade: 5 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-verde", categoria: "Iluminação", nome: "Fio De Luz De Tomada Verde", quantidade: 1 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-amarelo", categoria: "Iluminação", nome: "Fio De Luz De Tomada Amarelo", quantidade: 11 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-azul", categoria: "Iluminação", nome: "Fio De Luz De Tomada Azul", quantidade: 2 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-verde-e-rosa", categoria: "Iluminação", nome: "Fio De Luz De Tomada Verde E Rosa", quantidade: 1 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-lilas", categoria: "Iluminação", nome: "Fio De Luz De Tomada Lilás", quantidade: 2 },
  { id: "est-iluminacao-fio-de-luz-de-tomada-vermelho-e-amarelo", categoria: "Iluminação", nome: "Fio De Luz De Tomada Vermelho E Amarelo", quantidade: 1 },
  { id: "est-tapetes-verde-agua-gde", categoria: "Tapetes", nome: "Verde Agua Gde", quantidade: 2 },
  { id: "est-tapetes-rosa-gde", categoria: "Tapetes", nome: "Rosa Gde", quantidade: 5 },
  { id: "est-tapetes-lilas-gde", categoria: "Tapetes", nome: "Lilás Gde", quantidade: 2 },
  { id: "est-tapetes-branco-gde", categoria: "Tapetes", nome: "Branco Gde", quantidade: 3 },
  { id: "est-tapetes-tye-dye-medio", categoria: "Tapetes", nome: "Tye Dye Médio", quantidade: 2 },
  { id: "est-tapetes-azul-bebe", categoria: "Tapetes", nome: "Azul Bebe", quantidade: 2 },
  { id: "est-tapetes-bege", categoria: "Tapetes", nome: "Bege", quantidade: 2 },
  { id: "est-tapetes-roxo-branco", categoria: "Tapetes", nome: "Roxo / Branco", quantidade: 1 },
  { id: "est-tapetes-tigre", categoria: "Tapetes", nome: "Tigre", quantidade: 1 },
  { id: "est-tapetes-capivara", categoria: "Tapetes", nome: "Capivara", quantidade: 1 },
  { id: "est-tapetes-tye-dye-pq", categoria: "Tapetes", nome: "Tye Dye Pq", quantidade: 2 },
  { id: "est-tapetes-coracao-rosa-pq", categoria: "Tapetes", nome: "Coração Rosa Pq", quantidade: 1 },
  { id: "est-tapetes-borboleta", categoria: "Tapetes", nome: "Borboleta", quantidade: 1 },
  { id: "est-tapetes-meia-bola-fut-pq", categoria: "Tapetes", nome: "Meia Bola Fut Pq", quantidade: 8 },
  { id: "est-tapetes-campo-fut-pq", categoria: "Tapetes", nome: "Campo Fut Pq", quantidade: 1 },
  { id: "est-colchonetes-preto", categoria: "Colchonetes", nome: "Preto", quantidade: 63 },
  { id: "est-colchonetes-branco", categoria: "Colchonetes", nome: "Branco", quantidade: 19 },
  { id: "est-colchonetes-azul", categoria: "Colchonetes", nome: "Azul", quantidade: 8 },
  { id: "est-colchonetes-sem-capa", categoria: "Colchonetes", nome: "Sem Capa", quantidade: 2 },
  { id: "est-extensoes-comprida-3-entradas", categoria: "Extensões", nome: "Comprida 3 Entradas", quantidade: 1 },
  { id: "est-extensoes-media-3-entradas", categoria: "Extensões", nome: "Média 3 Entradas", quantidade: 3 },
  { id: "est-extensoes-comprida-1-entrada", categoria: "Extensões", nome: "Comprida 1 Entrada", quantidade: 1 },
  { id: "est-extensoes-media-1-entreda", categoria: "Extensões", nome: "Média 1 Entreda", quantidade: 1 },
  { id: "est-bandejas-com-pezinho", categoria: "Bandejas", nome: "Com Pézinho", quantidade: 11 },
  { id: "est-bandejas-sem-pezinho", categoria: "Bandejas", nome: "Sem Pézinho", quantidade: 5 },
  { id: "est-caixas-rosa-pq", categoria: "Caixas", nome: "Rosa Pq", quantidade: 5 },
  { id: "est-caixas-verde-pq", categoria: "Caixas", nome: "Verde Pq", quantidade: 1 },
  { id: "est-caixas-rosa-gde", categoria: "Caixas", nome: "Rosa Gde", quantidade: 1 },
];
